url: "https://illus0r.github.io/slackshop.ru_stable"
descriptor: "проводит курс"
email: ivan@dianov.org                 #TODO #yourname@inbox.ru
vk: https://vk.com/orl1kov
phone: "+7 903 780-35-25"

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
  

collections:
  courses:
    output: true
    permalink: /:path/
  course_reviews:
    output: true
  

defaults:
  - scope:
      path: ""
      type: courses
    values:
      layout: course
